NginxModuleEnabled ON;
NginxModuleOtelSpanExporter otlp;
NginxModuleOtelExporterEndpoint otel-col:4317;
NginxModuleServiceName ngnix-proxy;
NginxModuleResolveBackends ON;
NginxModuleOtelSampler AlwaysOn;
NginxModuleOtelMaxQueueSize 2048;
NginxModuleOtelScheduledDelayMillis 5000;
NginxModuleOtelMaxExportBatchSize 512;
NginxModuleServiceNamespace production;
NginxModuleServiceInstanceId instance-1;
NginxModuleTraceAsError on;
NginxModuleRequestHeaders User-Agent,Host;